repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: 'https://github.com/psf/black'
    rev: 23.10.0
    hooks:
      - id: black
        args:
          - '--line-length=120'
  - repo: 'https://github.com/pycqa/isort'
    rev: 5.12.0
    hooks:
      - id: isort
        args:
          - '--profile'
          - black
  - repo: 'https://github.com/myint/docformatter'
    rev: v1.7.5
    hooks:
      - id: docformatter
        args:
          - '--in-place'
          - '--wrap-summaries'
          - '89'
          - '--wrap-descriptions'
          - '89'
  - repo: 'https://github.com/astral-sh/ruff-pre-commit'
    rev: v0.1.8
    hooks:
      - id: ruff
