# Generated by Django 5.0.4 on 2024-04-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vcards", "0003_remove_vcard_unique_qr_code_vcard_qr_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vcard",
            name="qr_code",
            field=models.ImageField(upload_to="media/qr_codes/"),
        ),
    ]
