# Generated by Django 5.0.4 on 2024-05-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vcards", "0005_alter_vcard_qr_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="vcard",
            name="vcard_file",
            field=models.FileField(default=None, upload_to="vcard_files/"),
            preserve_default=False,
        ),
    ]
